In [1]:
import pandas as pd
import numpy as np

## Import du dataset

In [2]:
with open("../data/eCO2mix_RTE_Annuel-Definitif_2023.xls", "rb") as f:
    print(f.read(8))

b'P\xe9rim\xe8tr'

In [3]:
df = pd.read_csv(
    "../data/eCO2mix_RTE_Annuel-Definitif_2023.xls",
    sep="\t",
    encoding="latin-1",
    index_col=False
)

## Exploration

In [4]:
df.head(5)

,Périmètre,Nature,Date,Heures,Consommation,Prévision J-1,Prévision J,Fioul,Charbon,Gaz,...,Hydraulique - Fil de l?eau + éclusée,Hydraulique - Lacs,Hydraulique - STEP turbinage,Bioénergies - Déchets,Bioénergies - Biomasse,Bioénergies - Biogaz,Stockage batterie,Déstockage batterie,Eolien terrestre,Eolien offshore
0,France,Données définitives,2023-01-01,00:00,47571.0,46600.0,48000.0,81.0,24.0,2418.0,...,4987.0,1224.0,743.0,534.0,431.0,333.0,0.0,0.0,14967.0,405.0
1,France,Données définitives,2023-01-01,00:15,NaN,46050.0,47500.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,France,Données définitives,2023-01-01,00:30,46342.0,45500.0,47000.0,68.0,24.0,2423.0,...,4792.0,1048.0,842.0,537.0,426.0,337.0,0.0,0.0,13847.0,404.0
3,France,Données définitives,2023-01-01,00:45,NaN,44650.0,46350.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,France,Données définitives,2023-01-01,01:00,44790.0,43800.0,45700.0,67.0,25.0,2445.0,...,4781.0,1195.0,891.0,537.0,426.0,338.0,0.0,0.0,11471.0,404.0

In [5]:
df.describe()

,Consommation,Prévision J-1,Prévision J,Fioul,Charbon,Gaz,Nucléaire,Eolien,Solaire,Hydraulique,...,Hydraulique - Fil de l?eau + éclusée,Hydraulique - Lacs,Hydraulique - STEP turbinage,Bioénergies - Déchets,Bioénergies - Biomasse,Bioénergies - Biogaz,Stockage batterie,Déstockage batterie,Eolien terrestre,Eolien offshore
count,17520.000000,35040.000000,35040.000000,17520.000000,17520.000000,17520.000000,17520.000000,17520.000000,17520.000000,17520.000000,...,17520.000000,17520.000000,17520.000000,17520.000000,17520.000000,17520.000000,17520.0,17520.0,17520.000000,17520.000000
mean,49722.932877,48591.961187,48580.407078,108.707420,94.299543,3322.498116,36551.817295,5806.554224,2534.765240,6633.339726,...,4364.943436,1693.275057,575.118037,475.058619,368.427626,334.013470,0.0,0.0,5591.129338,215.546005
std,10338.621279,10312.586140,10185.245677,150.548494,242.778210,2424.243055,4739.139896,4257.461883,3577.232152,2688.182715,...,1414.309232,1145.645148,679.946577,46.627975,59.966599,11.006769,0.0,0.0,4119.042383,190.300891
min,29798.000000,27500.000000,28400.000000,27.000000,0.000000,280.000000,21498.000000,129.000000,0.000000,1762.000000,...,1464.000000,64.000000,2.000000,335.000000,201.000000,263.000000,0.0,0.0,130.000000,0.000000
25%,42215.750000,41000.000000,41200.000000,57.000000,15.000000,1538.000000,33365.750000,2355.750000,0.000000,4580.000000,...,3065.000000,843.000000,13.000000,440.000000,337.000000,327.000000,0.0,0.0,2274.750000,46.000000
50%,48299.500000,47100.000000,47050.000000,76.000000,19.000000,2722.000000,35720.500000,4643.500000,64.000000,6373.500000,...,4570.000000,1422.000000,335.000000,475.000000,361.000000,334.000000,0.0,0.0,4444.000000,165.000000
75%,56159.000000,54850.000000,54700.000000,95.000000,23.000000,4267.000000,40221.250000,8185.250000,4693.750000,8242.250000,...,5583.000000,2231.000000,872.000000,509.000000,387.000000,342.000000,0.0,0.0,7874.250000,364.000000
max,83757.000000,83000.000000,83500.000000,1563.000000,1754.000000,9974.000000,48444.000000,18254.000000,13395.000000,17947.000000,...,7442.000000,6991.000000,4094.000000,607.000000,556.000000,368.000000,0.0,0.0,17930.000000,705.000000

## Datacard

In [6]:
from datetime import datetime
import yaml

In [7]:
n = len(df)

datacard = {
    "name": "eCO2mix_RTE_Annuel-Definitif_2023",
    "version": "1.0",
    "created": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    "domain": "energy",
    "period": "2023",
    "data": {
        "instance_count": n,
        "feature_count": df.shape[1],
        "feature_list": {},
    }
}

description = {
    "Périmètre": "Texte - France",
    "Nature": "Données temps réel / Données consolidées / Données définitives",
    "Date": "Date du jour (jj/mm/aaaa)",
    "Heures": "Point horaire par pas de 15 minutes (hh:mm)",
    "Consommation": "Consommation en MW",
    "Prévision J-1": "Prévision J-1 de consommation en MW",
    "Prévision J": "Prévision J de consommation en MW",
    "Fioul": "Production fioul en MW",
    "Charbon": "Production charbon en MW",
    "Gaz": "Production gaz en MW",
    "Nucléaire": "Production nucléaire en MW",
    "Eolien": "Production éolienne en MW",
    "Solaire": "Production solaire en MW",
    "Hydraulique": "Production hydraulique en MW",
    "Pompage": "Pompage hydraulique en MW",
    "Bioénergies": "Production Bioénergies en MW",
    "Ech. physiques": "Solde imports/exports (flux physiques) en MW",
    "Taux de CO2": "Estimation des émissions de CO2 en g/kWh",
    "Ech. comm. Angleterre": "Solde imports/exports Angleterre (programmes d'échanges commerciaux) en MW",
    "Ech. comm. Espagne": "Solde imports/exports Espagne (programmes d'échanges commerciaux) en MW",
    "Ech. comm. Italie": "Solde imports/exports Italie (programmes d'échanges commerciaux) en MW",
    "Ech. comm. Suisse": "Solde imports/exports Suisse (programmes d'échanges commerciaux) en MW",
    "Ech. comm. Allemagne-Belgique": "Solde imports/exports Allemagne-Belgique (programmes d'échanges commerciaux) en MW",
    "Fioul - TAC": "Détail technologie turbine à combustion pour la filière fioul",
    "Fioul - Cogén.": "Détail technologie cogénération pour la filière fioul",
    "Fioul - Autres": "Détail autres technologies pour la filière fioul",
    "Gaz - TAC": "Détail technologie turbine à combustion pour la filière gaz",
    "Gaz - Cogén.": "Détail technologie cogénération pour la filière gaz",
    "Gaz - CCG": "Détail technologie cycle combiné gaz pour la filière gaz",
    "Gaz - Autres": "Détail autres technologies pour la filière gaz",
    "Hydraulique - Fil de l'eau + éclusée": "Détail technologie fil de l'eau et éclusée pour la filière hydraulique",
    "Hydraulique - Lacs": "Détail technologie lacs pour la filière hydraulique",
    "Hydraulique - STEP turbinage": "Détail technologie STEP turbinage pour la filière hydraulique",
    "Bioénergies - Déchets": "Détail technologie déchets pour la filière Bioénergies",
    "Bioénergies - Biomasse": "Détail technologie biomasse pour la filière Bioénergies",
    "Bioénergies - Biogaz": "Détail technologie biogaz pour la filière Bioénergies",
    "Stockage batterie": "Détail soutirage batteries",
    "Déstockage batterie": "Détail injections batteries",
    "Eolien terrestre": "Détail technologie éolien terrestre pour la filière Eolien",
    "Eolien offshore": "Détail technologie éolien en mer pour la filière Eolien",
}

count = df.count()
nunique = df.nunique()
missing = df.isna().sum()

df_stats = pd.DataFrame({
    "count": count.astype(int),
    "unique_count": nunique.astype(int),
    "duplicate_count": (count - nunique).astype(int),
    "duplicate_ratio": ((count - nunique) / count).round(2).astype(float),
    "missing_count": missing.astype(int),
    "missing_ratio": (missing / n).round(2).astype(float),
})
describe = df.describe().astype(float)

for idx, row in df_stats.iterrows():
    card = {
        "description": description.get(idx, ""),
        "type": str(df[idx].dtypes),
        "stats": row.to_dict(),
        "sample": df[idx].dropna().unique()[:5].tolist()
    }

    if pd.api.types.is_numeric_dtype(df[idx]):
        card.update({
            'stats': {
                **row.to_dict(),
                **describe[idx].to_dict()
            }
        })

    datacard["data"]["feature_list"][idx] = card

In [8]:
with open("../data/raw_data.yaml", "w", encoding="utf-8") as f:
    yaml.safe_dump(datacard, f, sort_keys=False, allow_unicode=True)